"""
Project lifecycle services:

* materialize  — turn an agent blueprint into tracked milestone/task rows
* recompute    — roll task statuses up into progress / next-task / phase
* serialize    — ORM -> ProjectOut (frontend contract, camelCase)
* context      — ORM -> plain dict for the agent layer
* progress     — ProgressOut summary incl. Progress Agent recommendations
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.agents import progress_agent
from app.models.project import Activity, Milestone, Project, Task
from app.models.user import User
from app.schemas.project import (
    ActivityOut,
    Blueprint,
    MilestoneOut,
    ProjectInput,
    ProjectOut,
    TaskOut,
)
from app.schemas.progress import MilestoneProgress, ProgressOut, ProgressTaskRef, StatusCounts, WeekLoad

SEV_RANK = {"Low": 1, "Medium": 2, "High": 3}


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _new_id() -> str:
    return str(uuid.uuid4())


# ---------------------------------------------------------------- materialize

def risk_level_from(blueprint: dict[str, Any]) -> str:
    risks = blueprint.get("risks", [])
    if not risks:
        return "low"
    score = max(SEV_RANK.get(r.get("severity", "Low"), 1) * SEV_RANK.get(r.get("probability", "Low"), 1) for r in risks)
    return "high" if score >= 6 else ("medium" if score >= 4 else "low")


def materialize_project(
    db: Session,
    student: User,
    inp: ProjectInput,
    blueprint: dict[str, Any],
    agent_logs: list[dict[str, Any]] | None = None,
) -> Project:
    """Create the Project row plus milestones/tasks/activity from a blueprint (camelCase dict)."""
    input_json = inp.model_dump(by_alias=True)
    timeline: list[dict[str, Any]] = blueprint.get("timeline", [])

    # Milestones: consecutive weeks sharing a phase collapse into one milestone.
    milestones: list[Milestone] = []
    for w in timeline:
        if milestones and milestones[-1].title == w.get("phase"):
            milestones[-1].week_end = int(w.get("week", milestones[-1].week_end))
        else:
            milestones.append(
                Milestone(
                    id=_new_id(),
                    project_id="",
                    title=str(w.get("phase", "Phase")),
                    week_start=int(w.get("week", 1)),
                    week_end=int(w.get("week", 1)),
                    order=len(milestones),
                )
            )

    def milestone_for_week(week: int) -> Milestone:
        for m in milestones:
            if m.week_start <= week <= m.week_end:
                return m
        fallback = Milestone(id=_new_id(), project_id="", title="Delivery", week_start=1, week_end=week, order=len(milestones))
        milestones.append(fallback)  # keep it attached so the FK can resolve
        return fallback

    project = Project(
        id=_new_id(),
        title=inp.title,
        domain=inp.domain,
        level=inp.level,
        student_id=student.id,
        team_size=inp.team_size,
        duration_weeks=inp.duration_weeks,
        current_week=1,
        phase=timeline[0].get("phase", "Planning & Design") if timeline else "Planning & Design",
        status="planning",
        risk_level=risk_level_from(blueprint),
        input=input_json,
        blueprint=blueprint,
        agent_logs=agent_logs,
        generated_at=_now(),
    )

    tasks: list[Task] = []
    order = 0
    for w in timeline:
        week = int(w.get("week", 1))
        ms = milestone_for_week(week)
        for title in w.get("tasks", []):
            tasks.append(Task(id=_new_id(), milestone_id=ms.id, title=str(title), week=week, status="pending", order=order))
            order += 1

    # First task of week 1 starts in progress.
    if tasks:
        tasks[0].status = "in-progress"

    now = _now()
    project.activity.append(
        Activity(id=_new_id(), text=f"Project blueprint generated by {len(agent_logs) if agent_logs else 5} agents", kind="ai", ts=now)
    )
    project.activity.append(Activity(id=_new_id(), text="Project created", kind="system", ts=now))

    # Relationship cascade assigns project_id on every child at flush time.
    project.milestones = milestones
    project.tasks = tasks
    project.student = student
    db.add(project)
    db.flush()

    _recompute_in_place(project)
    db.commit()
    db.refresh(project)
    project.student = student
    return project


# ---------------------------------------------------------------- recompute

def _next_task(project: Project) -> str:
    for t in project.tasks:
        if t.status == "in-progress":
            return t.title
    pending = sorted((t for t in project.tasks if t.status == "pending"), key=lambda t: (t.week, t.order))
    if pending:
        return pending[0].title
    delayed = [t for t in project.tasks if t.status == "delayed"]
    if delayed:
        return delayed[0].title
    return "Prepare final submission"


def _recompute_in_place(project: Project) -> None:
    tasks = project.tasks
    total = len(tasks)
    done = sum(1 for t in tasks if t.status == "done")
    project.progress = round((done / total) * 100) if total else 0
    project.next_task = _next_task(project)
    project.last_update = _now()

    all_done = total > 0 and done == total
    if all_done:
        project.status = "completed"
        project.phase = "Submitted"
    elif project.status == "completed":
        project.status = "active"

    # Phase follows the current week's plan when available.
    bp = project.blueprint or {}
    for w in bp.get("timeline", []):
        if int(w.get("week", -1)) == project.current_week and not all_done:
            project.phase = w.get("phase", project.phase)
            break


def update_task_status(db: Session, project: Project, task_id: str, status: str) -> Project:
    task = next((t for t in project.tasks if t.id == task_id), None)
    if task is None:
        raise LookupError("Task not found")
    old = task.status
    task.status = status
    _recompute_in_place(project)
    label = "completed" if status == "done" else f"moved {old} → {status}"
    project.activity.insert(0, Activity(id=_new_id(), project_id=project.id, text=f"Task {label}: {task.title}", kind="user", ts=_now()))
    db.commit()
    db.refresh(project)
    return project


def log_activity(db: Session, project: Project, text: str, kind: str = "ai") -> None:
    project.activity.insert(0, Activity(id=_new_id(), project_id=project.id, text=text, kind=kind, ts=_now()))
    project.last_update = _now()
    db.commit()


# ---------------------------------------------------------------- queries

def _eager():
    return [
        selectinload(Project.milestones),
        selectinload(Project.tasks),
        selectinload(Project.activity),
        selectinload(Project.student),
    ]


def load_project(db: Session, project_id: str) -> Project | None:
    stmt = select(Project).options(*_eager()).where(Project.id == project_id)
    return db.scalars(stmt).first()


def list_projects(db: Session, user: User) -> list[Project]:
    stmt = select(Project).options(*_eager())
    if user.role != "faculty":
        stmt = stmt.where(Project.student_id == user.id)
    stmt = stmt.order_by(Project.created_at.desc())
    return list(db.scalars(stmt))


# ---------------------------------------------------------------- serialization

def to_out(project: Project) -> ProjectOut:
    blueprint = Blueprint.model_validate(project.blueprint) if project.blueprint else None
    return ProjectOut(
        id=project.id,
        title=project.title,
        domain=project.domain,
        level=project.level,
        student_name=project.student.name if project.student else "",
        student_id=project.student_id,
        team_size=project.team_size,
        duration_weeks=project.duration_weeks,
        current_week=project.current_week,
        progress=project.progress,
        phase=project.phase,
        status=project.status,  # type: ignore[arg-type]
        risk_level=project.risk_level,  # type: ignore[arg-type]
        next_task=project.next_task,
        created_at=project.created_at,
        last_update=project.last_update,
        input=project.input,
        blueprint=blueprint,
        milestones=[MilestoneOut(id=m.id, title=m.title, weeks=[m.week_start, m.week_end]) for m in project.milestones],
        tasks=[TaskOut(id=t.id, title=t.title, week=t.week, milestone_id=t.milestone_id, status=t.status) for t in project.tasks],  # type: ignore[arg-type]
        activity=[ActivityOut(id=a.id, text=a.text, ts=a.ts, kind=a.kind) for a in project.activity],
    )


def to_context(project: Project) -> dict[str, Any]:
    """Plain camelCase dict consumed by doc/chat/progress/insights agents."""
    return {
        "title": project.title,
        "domain": project.domain,
        "level": project.level,
        "studentName": project.student.name if project.student else "",
        "teamSize": project.team_size,
        "durationWeeks": project.duration_weeks,
        "currentWeek": project.current_week,
        "progress": project.progress,
        "phase": project.phase,
        "status": project.status,
        "riskLevel": project.risk_level,
        "nextTask": project.next_task,
        "input": project.input,
        "blueprint": project.blueprint or {},
        "milestones": [{"id": m.id, "title": m.title, "weeks": [m.week_start, m.week_end]} for m in project.milestones],
        "tasks": [{"id": t.id, "title": t.title, "week": t.week, "status": t.status} for t in project.tasks],
    }


# ---------------------------------------------------------------- progress summary

def milestone_progress(project: Project, milestone: Milestone) -> int:
    tasks = [t for t in project.tasks if t.milestone_id == milestone.id]
    if not tasks:
        return 0
    return round(sum(1 for t in tasks if t.status == "done") / len(tasks) * 100)


def progress_summary(project: Project) -> ProgressOut:
    ctx = to_context(project)
    weeks = [
        WeekLoad(
            week=w,
            done=sum(1 for t in project.tasks if t.week == w and t.status == "done"),
            open=sum(1 for t in project.tasks if t.week == w and t.status in ("pending", "in-progress")),
            delayed=sum(1 for t in project.tasks if t.week == w and t.status == "delayed"),
        )
        for w in range(1, project.duration_weeks + 1)
    ]
    return ProgressOut(
        progress=project.progress,
        planned=round((project.current_week / max(project.duration_weeks, 1)) * 100),
        week=project.current_week,
        duration_weeks=project.duration_weeks,
        phase=project.phase,
        next_task=project.next_task,
        counts=StatusCounts(
            done=sum(1 for t in project.tasks if t.status == "done"),
            in_progress=sum(1 for t in project.tasks if t.status == "in-progress"),
            pending=sum(1 for t in project.tasks if t.status == "pending"),
            delayed=sum(1 for t in project.tasks if t.status == "delayed"),
        ),
        milestones=[
            MilestoneProgress(id=m.id, title=m.title, weeks=[m.week_start, m.week_end], progress=milestone_progress(project, m))
            for m in project.milestones
        ],
        weeks=weeks,
        tasks=[ProgressTaskRef(id=t.id, status=t.status) for t in project.tasks],
        recommendations=progress_agent.recommend(ctx),
    )
